# Generated by Django 5.0.6 on 2024-06-13 11:13

import account.utility
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=4)),
                ('account_number', models.CharField(default=account.utility.generate_account_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account_type', models.CharField(choices=[('S', 'SAVINGS'), ('C', 'CURRENT'), ('D', 'DOM')], default='s', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Type', models.CharField(choices=[('Deb', 'DEBIT'), ('Cre', 'CREDIT'), ('TRA', 'TRANSFER')], default='CRE', max_length=3)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('transaction_status', models.CharField(choices=[('S', 'SUCCESSFUL'), ('F', 'FAIL'), ('P', 'PENDING')], default='s', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
