# Generated by Django 5.0.6 on 2024-07-05 08:42

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(default='0000', max_length=4, validators=[account.validators.validate_pin]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Type',
            field=models.CharField(default='CRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=25),
        ),
    ]
